name: CI

on:
    push:
        branches:
            - master
    pull_request:

jobs:

    build:

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                php: ['7.4', '8.0']
                include:
                    - php: '8.0'
                      composer-options: '--ignore-platform-reqs'

        steps:

            -   name: Configure Git
                if: ${{ matrix.os == 'windows-latest' }}
                run: |
                    git config --system core.autocrlf false
                    git config --system core.eol lf

            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2 # https://github.com/shivammathur/setup-php
              with:
                  php-version: ${{ matrix.php }}
                  extensions: json
                  tools: composer:v2
                  coverage: pcov

            - name: Get Composer cache directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }}

            - name: Validate ruleset
              run: composer test
